import React from 'react';
import { Printer, ArrowLeft, ShieldCheck } from 'lucide-react';
import { ThermoplasticsLogo } from '../components/ThermoplasticsLogo';
import {
  InterventionRequest,
  MaintenanceOrder,
  Machine,
  Mold,
  StockItem,
} from '../types/gmao';

interface AuditReportViewProps {
  requests: InterventionRequest[];
  orders: MaintenanceOrder[];
  machines: Machine[];
  molds: Mold[];
  stock: StockItem[];
  onBack: () => void;
}

export const AuditReportView: React.FC<AuditReportViewProps> = ({
  requests,
  orders,
  machines,
  molds,
  stock,
  onBack,
}) => {
  const handlePrint = () => {
    window.print();
  };

  const runningMachines = machines.filter((m) => m.status === 'Running').length;
  const machineAvailabilityRate = machines.length > 0 ? ((runningMachines / machines.length) * 100).toFixed(1) : '100.0';
  const lowStockCount = stock.filter((s) => s.currentQty <= s.minQty).length;
  const waitingOrdersCount = orders.filter((o) => o.status === 'Waiting').length;

  return (
    <div className="p-8 max-w-[1200px] mx-auto space-y-8 animate-in fade-in duration-200">
      {/* Top Bar with Back and Print Actions */}
      <div className="flex items-center justify-between border-b border-neutral-300 pb-4">
        <button
          onClick={onBack}
          className="flex items-center gap-2 text-sm font-bold text-neutral-800 hover:text-neutral-950 px-3 py-1.5 rounded-xl hover:bg-black/5 transition-colors"
        >
          <ArrowLeft className="w-4 h-4" />
          <span>Back to Dashboard</span>
        </button>

        <div className="flex items-center gap-3">
          <button
            onClick={handlePrint}
            className="flex items-center gap-2 px-5 py-2.5 bg-blue-600 hover:bg-blue-700 text-white rounded-xl text-sm font-bold shadow-xs transition-all"
          >
            <Printer className="w-4 h-4" />
            <span>Print / Save as PDF</span>
          </button>
        </div>
      </div>

      {/* Main Document Body */}
      <div className="bg-white rounded-3xl p-8 border border-neutral-300 shadow-sm space-y-6">
        {/* Header */}
        <div className="flex items-start justify-between border-b pb-6">
          <ThermoplasticsLogo size="md" />
          <div className="text-right text-xs space-y-1 text-neutral-600">
            <div className="font-bold text-sm text-neutral-900">
              AUDIT & MAINTENANCE KPI SUMMARY
            </div>
            <div>Report Ref: <span className="font-mono font-bold">RPT-2026-SEP-W4</span></div>
            <div>Date: <span className="font-bold">25 September 2026</span></div>
            <div>Generated by: <span className="font-bold">Direction Maintenance &amp; GMAO</span></div>
            <div>Facility: <span className="font-bold">Z.I. Borj Cédria, Ben Arous, Tunisia</span></div>
          </div>
        </div>

        {/* KPI High-level Grid */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 text-center">
          <div className="p-4 bg-neutral-50 border border-neutral-200 rounded-2xl">
            <div className="text-xs font-semibold text-neutral-500 uppercase">Operational Availability</div>
            <div className="text-3xl font-black text-emerald-600 mt-1 tabular-nums">
              {machineAvailabilityRate}%
            </div>
            <div className="text-[11px] text-neutral-400 mt-1">{runningMachines} / {machines.length} active presses</div>
          </div>
          <div className="p-4 bg-neutral-50 border border-neutral-200 rounded-2xl">
            <div className="text-xs font-semibold text-neutral-500 uppercase">Open Work Orders</div>
            <div className="text-3xl font-black text-amber-600 mt-1 tabular-nums">
              {waitingOrdersCount}
            </div>
            <div className="text-[11px] text-neutral-400 mt-1">High priority pending</div>
          </div>
          <div className="p-4 bg-neutral-50 border border-neutral-200 rounded-2xl">
            <div className="text-xs font-semibold text-neutral-500 uppercase">Average Plant MTBF</div>
            <div className="text-3xl font-black text-blue-600 mt-1 tabular-nums">
              434 hrs
            </div>
            <div className="text-[11px] text-neutral-400 mt-1">Target: &gt; 400 hrs</div>
          </div>
          <div className="p-4 bg-neutral-50 border border-neutral-200 rounded-2xl">
            <div className="text-xs font-semibold text-neutral-500 uppercase">Critical Spare Alert</div>
            <div className="text-3xl font-black text-red-600 mt-1 tabular-nums">
              {lowStockCount}
            </div>
            <div className="text-[11px] text-neutral-400 mt-1">Below safety stock</div>
          </div>
        </div>

        {/* Machine Fleet Status Table */}
        <div className="space-y-3">
          <div className="text-sm font-bold text-neutral-900 uppercase tracking-wider flex items-center gap-2">
            <ShieldCheck className="w-4 h-4 text-blue-600" />
            <span>Injection Molding Machinery Fleet Overview</span>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full text-xs text-left border-collapse border border-neutral-200 rounded-xl">
              <thead className="bg-neutral-100 text-neutral-700 font-bold">
                <tr>
                  <th className="p-2.5 border">Machine #</th>
                  <th className="p-2.5 border">Model & Force</th>
                  <th className="p-2.5 border">Location</th>
                  <th className="p-2.5 border">Active Mold</th>
                  <th className="p-2.5 border">Status</th>
                  <th className="p-2.5 border text-right">MTBF</th>
                  <th className="p-2.5 border text-right">MTTR</th>
                </tr>
              </thead>
              <tbody>
                {machines.map((m) => (
                  <tr key={m.id} className="border-b hover:bg-neutral-50">
                    <td className="p-2.5 font-mono font-bold text-neutral-900 border">{m.number}</td>
                    <td className="p-2.5 border">{m.brand} {m.model} ({m.clampingForceTons}T)</td>
                    <td className="p-2.5 font-mono border">{m.locationNumber}</td>
                    <td className="p-2.5 font-semibold border">{m.activeMoldRef || 'None'}</td>
                    <td className="p-2.5 border">
                      <span className={`px-2 py-0.5 rounded text-[11px] font-bold ${
                        m.status === 'Running' ? 'bg-emerald-100 text-emerald-800' :
                        m.status === 'Under Maintenance' ? 'bg-amber-100 text-amber-800' :
                        'bg-red-100 text-red-800'
                      }`}>
                        {m.status}
                      </span>
                    </td>
                    <td className="p-2.5 text-right font-mono border">{m.mtbfHours} h</td>
                    <td className="p-2.5 text-right font-mono border">{m.mttrHours} h</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Active Maintenance Orders Table */}
        <div className="space-y-3">
          <div className="text-sm font-bold text-neutral-900 uppercase tracking-wider">
            Recent Maintenance Work Orders (OT)
          </div>
          <div className="overflow-x-auto">
            <table className="w-full text-xs text-left border-collapse border border-neutral-200 rounded-xl">
              <thead className="bg-neutral-100 text-neutral-700 font-bold">
                <tr>
                  <th className="p-2.5 border">Date</th>
                  <th className="p-2.5 border">Ref OT</th>
                  <th className="p-2.5 border">Equipment</th>
                  <th className="p-2.5 border">Technician</th>
                  <th className="p-2.5 border">Priority</th>
                  <th className="p-2.5 border">Progress</th>
                  <th className="p-2.5 border">Status</th>
                </tr>
              </thead>
              <tbody>
                {orders.slice(0, 6).map((o) => (
                  <tr key={o.id} className="border-b">
                    <td className="p-2.5 font-mono border">{o.date}</td>
                    <td className="p-2.5 font-mono font-bold text-blue-700 border">{o.refOT}</td>
                    <td className="p-2.5 border">{o.equipmentName}</td>
                    <td className="p-2.5 border">{o.assignedTo}</td>
                    <td className="p-2.5 font-bold border">{o.priority}</td>
                    <td className="p-2.5 font-mono border">{o.validationProgress}%</td>
                    <td className="p-2.5 border">{o.status}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Signatures & Certification block */}
        <div className="pt-8 border-t flex justify-between text-xs text-neutral-600">
          <div>
            <div className="font-bold text-neutral-900">Maintenance Department</div>
            <div className="mt-8 border-t border-neutral-400 pt-1 w-48 font-semibold">Direction Maintenance</div>
          </div>
          <div>
            <div className="font-bold text-neutral-900">Plant Operations Director</div>
            <div className="mt-8 border-t border-neutral-400 pt-1 w-48 font-semibold">Certified & Approved</div>
          </div>
        </div>
      </div>
    </div>
  );
};
